{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhands.fullname" . }}-workspace
  namespace: {{ include "openhands.namespace" . }}
  labels:
    {{- include "openhands.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if and .Values.fileStore.enabled (not .Values.fileStore.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhands.fullname" . }}-filestore
  namespace: {{ include "openhands.namespace" . }}
  labels:
    {{- include "openhands.labels" . | nindent 4 }}
  {{- with .Values.fileStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.fileStore.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.fileStore.size | quote }}
  {{- if .Values.fileStore.storageClass }}
  {{- if (eq "-" .Values.fileStore.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.fileStore.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
